#create a cycle that searches through the text being searched
#using X variable
#& have it break the loop,

original_text= '''Post 2 (Question): In this document, Huey Long describes how he believes that America should redistribute its wealth to create old-age pensions by establishing limits on wealth and income. In contrast, Franklin Delano Roosevelt signed the Social Security Act which had employers and employees cooperate to create the employees' pension. Which method do you think would have benefitted America more during the Great Depression and why?'''

f=original_text.split()

#i want it to get position of f using list
#by getting pos.f(), i will be able to pipe that output into the second phase
print(f)

#cycle here:
#might need to concatenate arrays in order to search for a wanted_text using spaces/more word count; i.e.) my wanted_text = 'Huey Long' i want to then join 2 items of the text using the .join method to match
#depending on length of the split generated by wanted_text, then use that constant as a variable for joining each item of the text with the item adjacent to the items in the list
wanted_text='Huey'#what i want to find
if wanted_text in f:
    print(f'{f.index(wanted_text)} pos here')
    print(f[f.index(wanted_text)-3:f.index(wanted_text)+11])#first list gets context before the wanted text, second list gets more context after it
    print(' '.join(f[f.index(wanted_text)-3:f.index(wanted_text)+11]))
print(wanted_text in original_text)
#print("tru")

#this works like i wanted it to